#!/command/with-contenv bash
set -euo pipefail

mkdir -p /storage/config /storage/postgres /storage/redis /storage/minio \
         /storage/git /storage/backups

CFG=/storage/config/buzz.env
if [ ! -f "$CFG" ]; then
  echo "buzz-init: first boot — generating secrets into $CFG"
  umask 077
  cat > "$CFG" <<GEN
# Generated by buzz-once first boot $(date -u +%FT%TZ). Do not lose this file:
# BUZZ_RELAY_PRIVATE_KEY is the relay's identity and must survive restores.
BUZZ_RELAY_PRIVATE_KEY=$(openssl rand -hex 32)
BUZZ_GIT_HOOK_HMAC_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)
REDIS_PASSWORD=$(openssl rand -hex 24)
BUZZ_S3_ACCESS_KEY=$(openssl rand -hex 16)
BUZZ_S3_SECRET_KEY=$(openssl rand -hex 24)
GEN
fi
. /usr/local/lib/buzz-once/env.sh

chown -R postgres:postgres /storage/postgres
chown -R redis:redis /storage/redis
chown -R buzz:buzz /storage/minio /storage/git /storage/backups

PGDATA=/storage/postgres/17
PGBIN=/usr/lib/postgresql/17/bin
if [ ! -s "$PGDATA/PG_VERSION" ]; then
  echo "buzz-init: initdb"
  install -d -o postgres -g postgres "$PGDATA"
  PWFILE=$(mktemp); echo "$POSTGRES_PASSWORD" > "$PWFILE"; chown postgres "$PWFILE"
  s6-setuidgid postgres $PGBIN/initdb -D "$PGDATA" -U buzz --pwfile="$PWFILE" \
      --auth-host=scram-sha-256 --auth-local=peer -E UTF8
  rm -f "$PWFILE"
  cat >> "$PGDATA/postgresql.conf" <<PGC
listen_addresses = '127.0.0.1'
shared_buffers = 256MB
max_connections = 50
PGC
fi
